version: '3'

volumes:
  db-data:

services:

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql

  drupal:
    build: .
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - DRUPAL_HASH_SALT=${DRUPAL_HASH_SALT}
    depends_on:
      - database
    ports:
      - 8080:80
    # volumes:
      # - './private:/var/www/private:rw,delegated'
      # - './:/var/www:rw,delegated'

# Uncomment above line for local dev.
# Alternatively, only use the private file volume to simulate the cloud env.
