volumes:
  db-data:

services:

  database:
    image: mysql:8.0
    restart: always
    ports:
      - 33063:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
  drupal:
    build: .
    restart: always
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - DRUPAL_HASH_SALT=${DRUPAL_HASH_SALT}
    depends_on:
      - database
    ports:
      - 8081:80
    volumes:
      - './private:/var/www/private:rw,delegated'
      - './:/var/www:rw,delegated'
