version: '3'

volumes:
  db-data:

services:

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  drupal:
    build: .
    depends_on:
      - database
    ports:
      - 8080:80
    restart: always
