version: '3'

volumes:
  db-data:

services:

  database:
    image: mysql:latest
    restart: always
    ports:
      - 33062:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql

#  node:
#    build: ./docker/node
#    volumes:
#      - ./:/var/www
#    platform: linux/arm64
  drupal:
    #platform: linux/amd64
    build: .
    # image: tcfunksb/mat-drupal:latest
    restart: always
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - DRUPAL_HASH_SALT=${DRUPAL_HASH_SALT}
    depends_on:
      - database
    ports:
      - 8080:80
    volumes:
      - './private:/var/www/private:rw,delegated'
      # - './:/var/www:rw,delegated'
#  alpine-amd:
#    build: ./docker/alpine
#    volumes:
#      - './:/var/www:rw,delegated'
#    #platform: linux/arm64
#    platform: linux/amd64
#  alpine-arm:
#    build: ./docker/alpine
#    volumes:
#      - './:/var/www:rw,delegated'
#    platform: linux/arm64
#    #platform: linux/amd64
  node-arm:
    build: ./docker/node
    volumes:
      - './:/var/www:rw,delegated'
    platform: linux/arm64
    #platform: linux/amd64
  node-amd:
    build: ./docker/node
    volumes:
      - './:/var/www:rw,delegated'
    #platform: linux/arm64
    platform: linux/amd64
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
