<?php

/**
 * @file
 * Functions to support theming in the Pattern Lab theme.
 */

 /**
  * Implemenets template_preprocess_file_link().
  */
function emat_preprocess_file_link(&$variables) {

  if (isset($variables['link'])) {
    $variables['link']['#attributes'] = $variables['link']['#attributes'] ?? [];
    $variables['link']['#attributes']['class'] = $variables['link']['#attributes']['class'] ?? [];
    $variables['link']['#attributes']['class'][] = 'link';
  }

}
