<?php

/**
 * @file
 * Contains emat_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function emat_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the emat_blocks module.
    case 'help.page.emat_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom blocks for MAT site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function emat_blocks_theme() {
  return [
    'emat_hero_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
